# Generated by Django 4.1.6 on 2023-03-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brisk_app1', '0002_couponactive_vendor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Vendor_Phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deals',
            name='Business_Phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
