# Generated by Django 4.1.6 on 2023-02-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brisk_app1', '0003_user_location_alter_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Vendor')], default=1),
        ),
    ]
