# Generated by Django 4.1.6 on 2023-02-23 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brisk_app1', '0004_user_phonenumber_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='name',
        ),
    ]
