# Generated by Django 4.1.6 on 2023-04-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brisk_app1', '0004_alter_couponactive_deal_applicable_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorrequest',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='vendorrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
