# Generated by Django 4.1.6 on 2023-04-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brisk_app1', '0006_remove_vendorbusinessdetails_vendor_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponactive',
            name='Payment_Complete',
        ),
    ]
