# Generated by Django 4.1.6 on 2023-02-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brisk_app1', '0006_rename_name_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50)),
                ('BusinessName', models.CharField(blank=True, max_length=50)),
                ('phoneNumber', models.CharField(blank=True, max_length=50)),
                ('Location', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
