# Generated by Django 4.1.6 on 2023-04-12 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brisk_app1', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='Customer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
    ]
